### ISSUE TITLE
Hopper create False Positive

### ISSUE THREAD

**Issue by Momonche** [Updated-NoCheatPlus/NoCheatPlus#11]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-264 ~MC: 1.15.2~
detected: 1.15.2
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13.2-1.15|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.5.1-SNAPSHOT-b451 | ProtocolSupport v4.29-dev

### Describe the issue
When a player jump under a hopper,he gets rollback

### How to reproduce the issue
See the screen below
[NC+] MissClick failed Passable: tried to move into a block (bugged player of phase cheat) (VL15)

### Extra links/Videos (Including debug logs)
![ROpy84JHgQpT](https://user-images.githubusercontent.com/37519498/81472058-c2d55f80-91f5-11ea-9587-02656514b363.png)

**Comment by CaptainObvious0** [comment]
Issue has been fixed with 631d6ee . Looks like version 1.13 changed the shape of the hopper, so now it's actually split into two parts. So a player can both collide with the bottom center part and the top part of the hopper. Unfortunately NoCheatPlus does not attempt to fully model these blocks with subshapes. So a full fix for this issue would require more time and some rewrite/changes to how NoCheatPlus handles block shapes. For now NoCheatPlus will add the ign_passable flag to the block to skip checking for passable. If you don't want to allow players to phase through hoppers, you can remove the flag by adding `HOPPER: SOLID+GROUND+XZ100+GROUND_HEIGHT` to your config under the compatibility settings. Jumping directly below the hoppers will work, but you'll come across some problems with players try to jump up to the edges/top half of the hopper.

This issue may be looked into further down the road. I may have overlooked something that could be used as a better fix.
