### ISSUE TITLE
Sprint jumping after a given velocity FPs

### ISSUE THREAD

**Issue by ZeroFreeUsernames** [Updated-NoCheatPlus/NoCheatPlus#171]
### Full output of /ncp version
![image](https://user-images.githubusercontent.com/92864564/138095205-879fd3d8-2346-49d1-a93e-64a91ccf594a.png)

### Describe the issue
Video Showcase issues:
https://www.youtube.com/watch?v=YFpPOaC9jBg

There is an issue with sprint jumping immediately after landing after being given velocity. When the player lands they are flagged as running faster than they should, however the added speed is leftover from the given velocity.

Logs from the SurvivalFly debug for the violation moves:
```
[14:05:45] [Server thread/INFO]: VIOLATION 6.983704379128003 - onGround(from->to): false->false (tags=walkspeed+bunnyfly(8)+bunnyfly(8)+hspeed)
[14:05:45] [Server thread/INFO]: [MOVING_SURVIVALFLY]
OnGround: --- -> ---, jumpphase: 1, liftoff: NORMAL(0)
 Tick counters: keepFrictionTick= 0 , 
 hDist: 0.35(-0.007) / Allowed: 0.287
 vDist: 0.165(-0.083) / Expected diff: -0.016 / Allowed: 0.181 , setBackY: 114.0 (setBackYDistance: 1.166 / MaxJumpHeight: 1.35) , fdsq: 0.793
 hAcc: fcmh1.264(6)
 Tags: walkspeed+bunnyfly(7)+bunnyfly(7)+hspeed

[14:05:45] [Server thread/INFO]: VIOLATION 6.317328256849292 - onGround(from->to): false->false (tags=walkspeed+bunnyfly(7)+bunnyfly(7)+hspeed)
[14:05:45] [Server thread/INFO]: [MOVING_SURVIVALFLY] [Nitroholic_] 
OnGround: --- -> ---, jumpphase: 1, liftoff: NORMAL(0)
 Tick counters: keepFrictionTick= 0 , 
 hDist: 0.344(-0.006) / Allowed: 0.287
 vDist: 0.083(-0.082) / Expected diff: -0.016 / Allowed: 0.099 , setBackY: 114.0 (setBackYDistance: 1.249 / MaxJumpHeight: 1.35) , fdsq: 0.837
 hAcc: fcmh1.254(7)
 Tags: walkspeed+bunnyfriction+bunnyfly(6)
```

### How to reproduce the issue
Give the player a velocity then sprint jump on landing and observe a violation shortly after.

Code used in this example to give velocity:
```
Location location = player.getLocation().add(player.getLocation().getDirection().normalize().multiply(15)); // Arbitrary location ahead of player.
        Location loc = player.getLocation();
        
        double max = 10;
        Vector velocity = location.toVector().subtract(loc.toVector()).multiply(0.5);
        if (velocity.getX() > max || velocity.getZ() > max) {
            velocity.multiply(max / Math.max(velocity.getX(), velocity.getZ()));
        }

        velocity.setY(1);
        player.setVelocity(velocity);
```

### Any possible config options changed or plugins that may cause interference?
Using completely fresh vanilla config.

**Comment by Lysandr0** [comment]
For the first issue, NCP -for whatever reason- is not recognising the 1.8 native module (Running in Bukkit-API only), which will cause issues with block-shape definitions. Does it happen with the default build? (121 as of now)

Regarding the second one: a quick workaround would be to extend the exemption time or to add the horizontal velocity amount to NCP's internal bookkeeping, via `data#addHorizontalVelocity`, as the speed after landing on ground is still too high and doesn't fit into the bunny hop/bunny fly envelopes.

(@xaw3ep can likely give more info and hints on this one :) )

**Comment by ZeroFreeUsernames** [comment]
My apologies, it seems the first block bound issue was an error from my local environment. I can confirm it does not happen with the jar downloaded directly from jenkins. I have edited the original issue post to remove the first problem, however the second issue does still remain with the latest build.

**Comment by ZeroFreeUsernames** [comment]
It seems that this is an issue now but not in older builds as a result of the horizontal buffer only being used now for fully non in-air moves since this commit: https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/f96008ea3a1d5a6a0221506ff5862c366d6b4651#diff-695323687c716bfa7b23bf2d8e9935c19bb2b814890d9e4e2bfde492b74863d3R2122

What was the reason behind this particular change? Or at least would it be safe to disable/have a settings toggle? (e.g. strict hbuffer usage) I've found that reverting this check fixes this velocity issue as well as another FP I was looking into with small violations when running off the side of a block.

**Comment by Lysandr0** [comment]
Original intention was to make NCP less forgiving towards bunnyhop cheats and the like, because cheaters could (on paper) simply exploit it to hop a little faster than the envelopes set by NCP. (https://github.com/NoCheatPlus/Issues/issues/365#issuecomment-271159176)

In any case, stuff like this should be fixed properly, instead of allowing a generic buffer to cover things up, I think it was also subject to removal in asofold's plans, or at least to confine it to oddities and/or obscure edge cases. ([Roadmap](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Roadmap.md). Not sure if some of the stuff in there will ever get implemented however, for obvious reasons).

Edit: feel free to also post the "running off the side of a block" thing :)

Edit2: this could also be caused by a too strict queued velocity invalidation. The default config will invalidate queued velocity entries after 20 ticks / 140 move events (see: `checks.moving.velocity.activationcounter/activationticks`). Would be interesting to see if it still happens with much higher values.

**Comment by Lysandr0** [comment]
Horizontal buffer is now unbound from being consumed on ground only. However, I'll keep the ticket open since the root cause hasn't been addressed just yet.
From a brief testing session, I can also reproduce this scenario with just stop-flying in air at high speed and then falling: after all velocity is consumed, violations will stack up quickly until speed drops below allowed.
I'm fairly sure this wasn't an issue before (or was it? :) ) so I'll need to see the commit history to check for any relevant changes.

**Comment by Lysandr0** [comment]
(Closed on accident)
Does it look any better with build 123?

**Comment by ZeroFreeUsernames** [comment]
Hi, it does indeed seem like the sprinting after being given velocity is fixed on the latest build, at least for the situations which were flagging it before.

**Comment by Lysandr0** [comment]
Thank you for the feedback :)
Now, we'll have to see the effects on abuses/exploits (longjump)...
