### ISSUE TITLE
Sf horizontal speeding: too high bunnyfly speed modifier(s) + no setback on low-jump detection

### ISSUE THREAD

**Issue by ZethiaZ** [Updated-NoCheatPlus/NoCheatPlus#196]
### Full output of /ncp version
[23:26:59 INFO]: ╗Version information½
[23:26:59 INFO]: Server:
[23:26:59 INFO]: git-PaperSpigot-445 ~MC: 1.8.8~
[23:26:59 INFO]: Detected: 1.8.8
[23:26:59 INFO]: NoCheatPlus:
[23:26:59 INFO]: Plugin: 3.17-SNAPSHOT-Updated-2022_03_13-03_52
[23:26:59 INFO]: MCAccess: 1.4.6-1.18.1|? / Bukkit-API
[23:26:59 INFO]: Features:
[23:26:59 INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, MCAccessBukkit
[23:26:59 INFO]: checks: FastConsume, Gutenberg, AttackFrequency, FlyingFrequency, KeepAliveFrequency
[23:26:59 INFO]: defaults: pvpKnockBackVelocity
[23:26:59 INFO]: packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, CatchAllAdapter, NoSlow, Fight
[23:26:59 INFO]: Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
[23:26:59 INFO]: ╗Related Plugins½
[23:26:59 INFO]: ProtocolLib v4.8.0, ViaVersion v4.2.1

### Describe the issue
When using the speed mode NCP in my client, it bypasses without issue.

### How to reproduce the issue
Toggle speed mode NCP on Leet client.

### Extra links: video and/or debug log (instructions: https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players)
https://youtu.be/1OLCZ9koejY

### Any possible config options changed or plugins that may cause interference?
No, I am using the default configuration of NCP.

**Comment by Lysandr0** [comment]
We're planning to refactor (recode rather :p) SurvivalFly's horizontal handling, which also means that the bunnyhop mechanism will be replaced (a ticket about it will follow rather soon).
In the mean time, a few things:
* Would be interesting to see how much faster this is than vanilla bunnyhopping (sprint-jumping).
You can test this by using the `ncp stopwatch` command (Usually a distance of 100 blocks is enough - `/ncp stopwatch distance 100`).
* A debug log is much appreciated.
* I can't really tell from the video but is the player low-jumping? If so, that would require a fix for the low-jump detection rather.

**Comment by ZethiaZ** [comment]
![image](https://user-images.githubusercontent.com/48283890/159364563-19b5bcc9-56eb-4ecb-9d9e-e99695dc0707.png)

**Comment by ZethiaZ** [comment]
By debug log, do you just mean the file in the NCP plugin folder? Or is there a command to get a debug?

The player is lowjumping fyi.

**Comment by Lysandr0** [comment]
To create a debug log:
* Delete the previous .log file
* `/ncp reload` to generate a clean one
* `/ncp debug player [playername] yes:MOVING`
* Reproduce the issue
* `/ncp debug player [playername] no:MOVING`

Edit: with vanilla, I seem to average 14.4+- seconds (1,2+- seconds faster).
Looks like this is more of an issue with our constants/envelopes being a bit too loose, rather than an actual bypass. Will be fixed with the refactor mentioned above. 
I'm more interested to see if NCP is actually picking up the low-jump. 
NCP doesn't punish players on low-jumping, partly because vanilla allows it in some cases and for other reasons which have never been explicitly explained by asofold (@xaw3ep any ideas? (Aside from slopes, noob towering and such :p).

**Comment by ZethiaZ** [comment]
[nocheatplus.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/8338015/nocheatplus.log)

**Comment by ZethiaZ** [comment]
I tried to use pastebin but it only lets me if I become a pro user so it is what it is.

**Comment by Lysandr0** [comment]
(I do prefer having the log file actually :p )

Judging from the log, the low-jumping part is getting detected correctly, like I suspected.
As a fix, I'll try to identify and detect all legit low-jumping cases, so that we can finally punish players for it.
Fixing bunny would be a waste of time as of now, since the model will be recoded/replaced anyway.

**Comment by Lysandr0** [comment]
Latest commit https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/7f13311ec4fccf52bdb2c14c69f1eba1275a5600 on the Testing branch should address this.
The low-jump detection is now much, _much_ more strict:
* Bunnyflying is denied if in low-jump-descend phase (won't be able to sprint-jump at all).
* Low-jump will immediately yield a violation
* The detection now also contributes into feeding the Improbable check. This will penalise too many low-jump attempts in a row (Can't customise the fed amount as of now, and due to frequent processing of the check, a lower amount was choosen).
* If in low-jump, buffer can't be regained, but can be used (!);
* All known legit low-jumping cases have been taken care of (should've :p)

Denying buffer regain and bunnyhop might be unnecessarily harsh. New false positives might appear, also. So handle with care :p

**Comment by ZethiaZ** [comment]
I will compile and test that branch & tell y’all how it does.

**Comment by ZethiaZ** [comment]
This seems to more or less prevent the bypass and I haven't noticed any significant new falses, although im sure they exist.
