### ISSUE TITLE
[API] [Question] is it possible to adopt custom logger with api?

### ISSUE THREAD

**Issue by giqnt** [Updated-NoCheatPlus/NoCheatPlus#198]
is it possible to adopt custom file logger with api?
i want to replace file with mysql.

if it's not possible, i'm willing to pull request new api myself, well, if you dont want to do it by yourself.

(btw, is it only me that some ncp code looks a little bit... dirty..?)

**Comment by Lysandr0** [comment]
Depends on which parts of code we are talking about, but yes, it definitely could use some improvements :)
NCP’s infrastructure hasn’t been touched since 2018 (when asofold left) due to its overall complexity.
You can have a look at the [fundamentals](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Fundamentals.md) page for further info concerning NCP's design/future
 
Any PR that can help making the code more inviting/clean are much appreciated, however such will need Xaw3ep or CaptainObvious approval, so it could take quite a bit of time to review.

**Comment by giqnt** [comment]
Well, thanks!
but that was my sub-question..

is it possible to adopt custom file logger with api?
i want to replace file with mysql.

**Comment by giqnt** [comment]
oh and is there javadoc?

**Comment by xaw3ep** [comment]
Afraid there is no java-doc. 
Back to your primary question, moving the log from file to database is not possible. 
But if you only want to record who violated, what checks they failed, total or added(violation), then making a hook will help

But how to make a hook?
You can see this wiki:
https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/API.md
The wiki is hard to understand? Here are some examples:
https://github.com/xaw3ep/NCPDragDown/tree/master/NCPDragDown/scr/pl/xayanix/ncpdragdown
https://github.com/Updated-NoCheatPlus/NoCheatPlus/blob/master/NCPPlugin/src/main/java/fr/neatmonster/nocheatplus/hooks/allviolations/AllViolationsHook.java

**Comment by giqnt** [comment]
Ok thanks and solved!
