### ISSUE TITLE
Plugin errors and Visaversion false flag + bypassed some

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#213]
1. The server is a false alarm when the server is on 1.12.2 and I am, for example, on 1.16.5 in the water 2. for example, I forgot to finish in the log about the check, for example: evnelope:0:5 and I forgot to write 0:5 and there were plugin errors, but the configuration itself was not reset, but only errors were written. 3. This error is already me and some person in the discord. Here it is: [NoCheatPlus] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.

Latest build.

Bypassed:
Entityspeed 2(impact) riding no saddle.
Timer 1.07 impact

**Comment by rautamiekka** [comment]
> Latest build.

Invalid (non-existent) version number.

**Comment by ghost** [comment]
140

**Comment by Lysandr0** [comment]
Please follow the issue template next time :)
1) Currently NCP doesn't support client-specific features on older servers and vice versa. Such support may come in the future, but no promises here. :p
2) To set up a custom config have a look at the documentation: https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/General.md#set-up-a-custom-configuration
3) For the error, we'll need:
* A *full* output of the /ncp version command;
* The full error's stacktrace.

Edit: forgot about the two "bypasses" 😛 
1) MorePackets can catch low timer cheats at the cost of being more susceptible to client-side lag. Again, you can have a look at the docs linked above to know how to configure it.
2) NCP is not equipped with a fully-fledged horizontal-speed handling for vehicles as of now, due to how flawed they are in Minecraft, which makes it harder for us to code a decent implementation/framework.
We have a simplistic speed "cap" just to prevent extremely fast speeding but nothing else.
