### ISSUE TITLE
boatsanywhere config is incorrect

### ISSUE THREAD

**Issue by Brokkonaut** [Updated-NoCheatPlus/NoCheatPlus#214]
Since some time the boatsanywhere config option is reversed so if i set preventmisc.boatsanywhere to false to not prevent placing boats, it is prevented. And when is set it to true to prevent it, it is not prevented.

This flag worked correctly for several years, but now it is broken.

**Comment by Lysandr0** [comment]
The flag's logic was reverted due to this kind of misunderstanding. However a renaming is likely more appropriate at this point (i.e.: boatsOnWaterOnly).
Anyhow, the flag should be interpreted as:
`boatsanywhere = false`-> Prevent players from placing down boats anywhere(= on ground) _but_ on water;
`boatsanywhere = true` -> Allow players to place boats on ground as well (effectively anywhere then).

**Comment by molor** [comment]
The problem is in parent `prevent...` section name, users (at least issue creator and me) expects that setting `prevent...`.`boats anywhere` to `true` will _prevent_ placing _boats anywhere_, but now it's allows placing instead, so meaning of the parent section name is just... ignored?

**Comment by Lysandr0** [comment]
Indeed the parent category is a bit misleading. 
I guess asofold had the intention of putting something else under the miscellaneous (`blockplace`) preventions category; but it's quite pointless with just the `boatsanywhere` flag.
Will remove the parent category + rename the flag in the next update, hopefully it will make things more intuitive.

**Comment by Brokkonaut** [comment]
I don't know if this should be a part of ncp at all, because it has nothing to do with cheating. placing boats on land is just a normal minecraft mechanic.

but if it is kept, is would really prefer to have it names so that a value of "false" means no action (-> allow boat placement), as it is with most (if not all) other config options.

**Comment by Lysandr0** [comment]
I guess it could be removed, too. 
The feature was first introduced in 2012/11, back when boats where virtually useless on the ground, so I guess the flag's purpose was to simply get rid of a questionable game-design choice / game inconsistency.
With the introduction of 1.9, boats were made somewhat useful for on ground use as well (thinking of ice+boats lanes in particular). So it doesn't make much sense to still maintain such feature, EXCEPT for the fact that it can prevent players from boat-flying in a waterless map, because vehicles are client-sided from 1.9 and onwards. 
Granted, we have the Vehicle.Envelope check for that, but it can further thwart a cheater's plan to use vehicle-related cheats. :p

**Comment by Lysandr0** [comment]
Done with https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/07bdc0ea10e5c12d2473fe61032b349ce605d8dd
The preventmisc category has been removed, and flag renamed to "boatsOnWaterOnly"
False = vanilla behaviour
True = will be able to place boats only on water.

**Comment by molor** [comment]
(but when it will be in master?)

**Comment by molor** [comment]
(what is `hspeed` branch and again when it will be in master?)

**Comment by molor** [comment]
(why you can't reply to me over a half of year and again, again when it will be in master?..)

**Comment by molor** [comment]
(@Lysandr0 ^ :/)

**Comment by Lysandr0** [comment]
I don't get notifications for closed issues, so.
We're currently stuck on a bunch of things, so it will take some time still.
