### ISSUE TITLE
NCP not detect killaura?

### ISSUE THREAD

**Issue by IAmOarcle** [Updated-NoCheatPlus/NoCheatPlus#238]

**Comment by rejomy** [comment]
I've already created a couple of tickets, so I'll just insert the coder's answer for you - NCP suite of combat checks won't detect anything other than impossible behaviour, such as hitting entities with one's back turned on them etc...
For more information, check the FAQ about killaura: https://github.com/Updated-NoCheatPlus/Docs/blob/master/FAQ.md#why-is-aimbotkillaura-not-detected-by-nocheatplus

In any case, an overhaul for fight checks is planned with the upcoming HitBox and Visible checks. Currently delayed because other work has been queueing since.

**Comment by Lysandr0** [comment]
Long story short, no.
Existing combat checks will be improved somehow, someway, but adding killaura checks is out of the question for us currently, due to the reasons mentioned above.

Having said that, this project is open-source, so if anyone wants to add/improve combat checks, they are much welcome to open PRs :)
