### ISSUE TITLE
Help me figure out the config

### ISSUE THREAD

**Issue by makksgam** [Updated-NoCheatPlus/NoCheatPlus#252]
Hello. I want to add a hidden swimmingspeed check to my NoCheatPlus config, but reading the wiki I didn't understand how to do it. Help please

My server core is paper 1.12.2 and I use viaversion to support 1.16.5 and on this version players complain that they are thrown in the water

And I also ran into the problem that if at 1.16.5 you stand on the snow that stands on the soul sand, you will be thrown back

**Comment by Lysandr0** [comment]
You'll have the add the entry `swimmingspeed: your-percentage-here` before the `checks.moving.survivalfly.extended` entry. Do note that this will allow faster swimming for *all* clients.

Regarding ViaVersion: 
* The swimming mechanic was introduced in 1.13. So of course 1.13+ clients swimming in older servers will generate false positives.
We currently do not support cross-version features (and we don't plan to support such thing anytime soon, because players can simply log back in with the appropriate client version).

* For the snow+soul sand thing you'll need to be more precise.
If it's a false positive, we prefer tickets to be split.

**Comment by makksgam** [comment]
Can I ask 1 more question here

I have a version of the server on which I am testing anti-cheat 1.12.2 and I myself logged in from 1.12.2, but when I try to take off using elytra, anti-cheat swears at me and throws me back

Here I uploaded a video from the tests:
https://youtu.be/qilgqJLsgcE

**Comment by Lysandr0** [comment]
That's a known issue for now. Elytra will get some touch ups down the line. :)
