### ISSUE TITLE
kicked for flying outside of Y 0 = 255 with mohist hybrid server and cubic chunks mod

### ISSUE THREAD

**Issue by realflow100** [Updated-NoCheatPlus/NoCheatPlus#37]
https://github.com/NoCheatPlus/Issues/issues/631

I posted there originally but the same also applies to this version.

I am using mohist to have plugins and forge at the same time so I can have cubic chunks mod.
but cubic chunks mod removing the height and depth limit causes severe issues. I cant play outside of Y 0 to 255 because i get kicked for "flying" because im able to build up and down for millions of blocks vertically. and cubic chunks removes the void and bedrock and its just caves and ores forever below Y 0. and your able to build up as high as you want millions of blocks into the sky as well.
NCP doesnt seem to like mods that extend the height limit. it thinks we are flying or not on a block for some reason.

Any ideas? is there something i can change in the config? or do I have to wait?

**Comment by xaw3ep** [comment]
I can deal with fly false-positive outside world but still not sure with weird fall damage bugs. Will take a look later!

**Comment by realflow100** [comment]
Yeah I tried turning things off in NCP one by one. and even with the flying and hover stuff disabled sometimes I would still take damage as if its forcing me to take void damage below Y 0 its super aggressive with everything enabled. rapidly hurting the player or kicking them

**Comment by Helinos** [comment]
I'm having the same issues on a similar setup.
I'm using Mohist in order to use the Cubic Chunks mod alongside spigot plugins. As far as I can tell there are only 2 problems with this version of NCP when using this specific setup:
1) Starting a fall from above Y=256 (And presumably below Y=0, but I am yet to test this) causes you to die from fall in the middle of the air after 100 blocks or so.
2) You aren't able to move nor break blocks at Y<=0 as you constantly set off SurvivalFly and FastBreak checks.

Oddly enough, the first problem can be remedied by installing PNCP.
I can provide logs or other information from my server if you ever become interested in taking look at this.

**Comment by realflow100** [comment]
I gave up on it shortly after my last post :( my dreams of a cubic chunks anarchy survival no cheats mohist server are down the drain :(
have to just allow cheats and PRAY nobody lags out or crashes the server or other players by flying really fast or speed hacking or using broken items or something.

**Comment by Lysandr0** [comment]
Flying/Building/Moving below y 0 should be fixed with "`minimalworldy`" (compatibility section of the config file, near the bottom)
Above 255 is another story. :)
Currently out of reach with the current development phase, will postpone this for a later time.
