### ISSUE TITLE
Better dealing with setbacks caused by spigots "moved too quickly" check

### ISSUE THREAD

**Issue by johndoe1Johndoe** [Updated-NoCheatPlus/NoCheatPlus#68]
### Full output of /ncp version
https://i.imgur.com/9l1yRro.png
### Describe the issue
basicaly you can leave any fight e.t.c. by activating ncpfly
### How to reproduce the issue
check vid
### Extra links/Videos (Including debug logs)
https://youtu.be/2f_hIz_N35s
https://hastebin.com/covevabiba
### Any possible config options changed or plugins that may cause interference?
dunno

**Comment by Xayanix** [comment]
https://www.spigotmc.org/resources/ncp-dragdown.55788/

**Comment by CaptainObvious0** [comment]
Video and hastebin seem removed/expired. But typically client devs refer to this as "PacketFly", where the client is abusing the "moved too quickly" check in spigot. It's caused by spigot teleporting the player after they fail the check, which causes NCP to reset some moving data and assume the teleport as what a normal teleport would be. In spigot 1.9+, they changed it so the moved too quickly check is done before the move event is called, meaning NCP never receives the move from the player and being able to setback the player on its own.

Overall, would require some hacky fix in NCP to account for this issue caused by spigot by attempting to deal with setbacks from spigot. My best recommendation at the moment would be to just disable spigots checks within spigot.yml, just know you're possibly opening yourself up to crash exploits but I believe NCP should cancel any extreme movements on its own and prevent any crash exploits that spigot was doing.

**Comment by Lysandr0** [comment]
Closing in favour of #231
