### ISSUE TITLE
Not work Griefprevention crops trample protection when use with nocheatplus without op permission

### ISSUE THREAD

**Issue by andris155** [Updated-NoCheatPlus/NoCheatPlus#8]
### Full output of /ncp version
```
[17:07:30 INFO]: ---- Version information ----
[17:07:30 INFO]: #### Server ####
[17:07:30 INFO]: git-Paper-234 ~MC: 1.15.2~
[17:07:30 INFO]:   detected: 1.15.2
[17:07:30 INFO]: #### NoCheatPlus ####
[17:07:30 INFO]: Plugin: 3.17-SNAPSHOT-b5.7.3
[17:07:30 INFO]: MCAccess: 1.13-1.15.2|? / Bukkit-API
[17:07:30 INFO]: Features:
[17:07:30 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
[17:07:30 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:07:30 INFO]:   defaults: pvpKnockBackVelocity
[17:07:30 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[17:07:30 INFO]: Hooks: MyPet 1.1 | ViolationFrequency~NCP~ 1.0
[17:07:30 INFO]: #### Related Plugins ####
[17:07:30 INFO]: ProtocolLib v4.5.0 | ConditionalCommands v1.5
```

### Describe the issue
Not work Griefprevention crops trample protection when use with nocheatplus without op permission.
Same issue with other some other protection plugins.

### How to reproduce the issue
1. Install NoCheatPlus and Griefprevention to your server.
2. Claim a land and plant crops.
3. Other players can trample the plants without op permission.

**Comment by andris155** [comment]
I tested and if disable nofall protection the Griefprevention crops trample protection works perfectly.
This is the nofall protection bug.

**Comment by CaptainObvious0** [comment]
NoCheatPlus fires a PlayerInteractEvent to check if the event is cancelled (by another plugin) before setting the farmland to dirt. So theoretically GriefProtection should have the chance to cancel the event and NoCheatPlus will not set the farmland to dirt if it does cancel the event. You only listed GriefProtection, but is this also an issue with WorldGuard? 

Regardless, I'll take a look at this issue when I can (and when I have more information).

**Comment by CaptainObvious0** [comment]
This seems to be an issue with GriefPrevention itself, and you will need to contact that developer in order to add compatibility with NoCheatPlus. The plugin does not attempt to cancel the players interact event, so NoCheatPlus will continue. I tested WorldGuard and it cancelled the event properly. 

I'm not familiar with GriefPrevention but maybe you can change some settings which will cancel any PlayerInteractEvents. As a workaround, you can also disable "dealdamage" in the config, just know that it will no longer attempt to damage the player if they're using NoFall hacks.

I'll be closing this issue as it is a problem with GriefPrevention rather than NoCheatPlus.

**Comment by Jikoo** [comment]
Why is NCP expecting plugins to cancel an interact event for a block that has no interaction under normal conditions?

Pretty sure the EntityChangeBlockEvent is fired usually but the docs suggest otherwise. For other block types (like lectern modification) a BlockPlaceEvent is fired with replacedBlockState being the old block. Either seems appropriate, and either would be handled by GP.

**Comment by RoboMWM** [comment]
Also, why is NCP changing blocks? Pretty sure damaging players who avoid fall damage doesn't also have to involve modifying farmland...

**Comment by CaptainObvious0** [comment]
> 
> 
> Why is NCP expecting plugins to cancel an interact event for a block that has no interaction under normal conditions?
> 
> Pretty sure the EntityChangeBlockEvent is fired usually but the docs suggest otherwise. For other block types (like lectern modification) a BlockPlaceEvent is fired with replacedBlockState being the old block. Either seems appropriate, and either would be handled by GP.

I believe two events are fired when the player tramples farmland. PlayerInteract and EntityChangeBlockEvent as you said. Thus why NCP will fire a PlayerInteractEvent before setting the block to dirt. I'll add support so that it will fire both events which will allow GriefPrevention to cancel the event. 

> 
> 
> Also, why is NCP changing blocks? Pretty sure damaging players who avoid fall damage doesn't also have to involve modifying farmland...

It doesn't just damage the player when they're suspected of cheating, the NoFall check takes over all fall damage. All fall distance and such is calculated within NCP and dealt accordingly, so when the check is enabled all fall damage is done by NCP. I believe this is why it needs to also allow for farmland trampling, unless it's there for another reason. I can test it out, see if farmland is still trampled without having to modify the block.

**Comment by CaptainObvious0** [comment]
EntityChangeBlockEvent is now fired alongside PlayerInteractEvent. From my testing it will now allow GriefPrevention to cancel the event and it will no longer be set to dirt. (de135cb)
