### ISSUE TITLE
CreativeFly false positive with elytra (+fireworks)

### ISSUE THREAD

**Issue by JimusHimus** [Updated-NoCheatPlus/NoCheatPlus#9]
![изображение](https://user-images.githubusercontent.com/39002687/81116182-95569080-8f2d-11ea-9c5e-0d4e9ed4f292.png)

I'm trying to take off with elytra, ncp shows CreativeFly.
If CreativeFly disabled it shows SurvivalFly.
It seems to me that fireworks make the problem bigger and they are not the main factor.
Also seems slabs and fences also somehow influence.

### How to reproduce the issue
Do the same as in the video

### Extra links/Videos (Including debug logs)
https://dl.dropboxusercontent.com/s/536fo5kp00indbc/2020-05-06%2000-02-11.mp4
https://dl.dropboxusercontent.com/s/tg330qdj7e98p63/2020-05-06%2000-03-40.mp4
Logs:
https://pastebin.com/hC2gdCqw

### Any possible config options changed or plugins that may cause interference?
No related options changed

**Comment by CaptainObvious0** [comment]
I've having issues reproducing this issue, but you're not the first to report problems with Elytra. I tested fireworks and elytra flight on both a 1.15 client and 1.13 client and found no issues. Here's a video of my test on a 1.15 client: https://youtu.be/53SzhWNf9ZE

If you could reproduce the issue and create a debug log, that will help with determining what the issue is. If you're not sure how to create a debug log, follow the steps below.

Navigate to your NoCheatPlus folder and find 'nocheatplus.log'. Open the file and clear everything to  make sure no old data is included. In game, type `/ncp debug player (player)` to start debugging the player. Reproduce the issue, and then navigate back to your log file. You can upload the file here or copy the contents into a website like pastebin and post the link.

**Comment by JimusHimus** [comment]
A bit like a floating bug. When I tried to repeat this NCP behaved better. But I managed to capture 2 errors in the console and a lot of visible moving.setCancelled.

Console:
[10:58:28 INFO]: [NC+] elletricity failed CreativeFly: tried to move unexpectedly while in air (Tags: hfrict+elytra_v_keep+vdist) (VL103)
[10:59:05 INFO]: [NC+] elletricity failed CreativeFly: tried to move unexpectedly while in air (Tags: hfrict+elytra_v_keep+vdist) (VL101)

nocheatplus.log, debug mode:
https://www.dropbox.com/s/2z6y4ow3be3fz24/paste.txt?dl=0

**Comment by CaptainObvious0** [comment]
Thanks for providing the debug log, much easier to trace the issue from that. Commit 7e0d7e should fix issues when first taking off with Elytra. 

I wasn't able to reproduce the issue so I'll need you to confirm if it has been fixed or not.

**Comment by JimusHimus** [comment]
Maybe a little better, but still a lot of issues.
[22:17:38 INFO]: [NC+] elletricity failed CreativeFly: tried to move unexpectedly while in air (Tags: hfrict+elytra_v_keep+vdist) (VL114)
https://pastebin.com/mSQGk8Qk

**Comment by JimusHimus** [comment]
More logs
![изображение](https://user-images.githubusercontent.com/39002687/81483170-b5939180-9244-11ea-8831-eb0b237f18a1.png)

[nocheatplus 2.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/4604351/nocheatplus.2.log)

**Comment by CaptainObvious0** [comment]
Another attempted fix with commit 1aee48a . Let me know if this fixes the issue.

**Comment by JimusHimus** [comment]
Just what the doctor ordered! Thank you!
