### ISSUE TITLE
Criticals false positive

### ISSUE THREAD

**Issue by AoElite** [Updated-NoCheatPlus/NoCheatPlus#92]
### Full output of /ncp version
Latest

### Describe the issue
Hitting a entity in a boat or a entity standing under a block causes a criticals false flag with mismatch. I checked the code and for some reason in the criticals check it compares the attacker's velocity with the entity's velocity. If the entity hit takes reduced velocity or none (in a boat, under a block) then it flags as it as a mismatch.

### How to reproduce the issue
Stated above

### Extra links/Videos (Including debug logs)
It's pretty simple to replicate 

### Any possible config options changed or plugins that may cause interference?
No other plugins installed

Also do you happen to have a discord or something so it's easier to communicate with you?

**Comment by Lysandr0** [comment]
The Discord server link can be found in the [readme/homepage.](https://github.com/Updated-NoCheatPlus/NoCheatPlus#nocheatplus)

For @xaw3ep:
https://www.dropbox.com/s/4sr2x8kusllx0uz/criticals_test.mov?dl=0
https://www.dropbox.com/s/w85h5915fw84dma/critical_test2.mov?dl=0
There seems to be something wrong with how NoFall calculates fall distance, it was fine prior to some builds ago, not sure what caused it.

Debug logs:
(From inside/on boat)
[Critical_log(on boat).log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/5742426/Critical_log.on.boat.log)

(From outside boat)
[Critical_log1(boat).log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/5742427/Critical_log1.boat.log)

(Running around hitting entities on normal conditions)
[Critical_log(normal).log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/5742428/Critical_log.normal.log)

**Note:** I have reverted back Y_ON_GROUND_DEFAULT to 0.016 for all tests, instead of 0.025

Edit: The videos' quality got butchered unfortunately, sorry about that.
